#!/bin/sh

POSIXLY_CORRECT=yes

## filtr-prikaz-meno-log

# skontroluj, ci jesto veci dvesto
# ak jesto, cas prikazom dat priestor

# filtruj info (awk), zoradzuj (abc)
#######################################
# -z $1 == "list"
# -n $1 == "list" || "help" || "status" || "profit" || "status-currency"
# -n $1 || $2 == "[name]"
# -n $2 || $3 == "[log]"
# || solved by shift

# return take from xtf (orgsrc)
#######################################
# WARNING: desetine, none else :/


# [-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...]]

if [ $1 = "-h" ] || [ $1 = "--help" ]; then
  echo "Hello!"
  echo "Here's some help:\n\n"
  echo "[-h|--help] [FILTR] [PŘÍKAZ] UŽIVATEL LOG [LOG2 [...]]"
  echo "'-h' or '--help' :   is what you can see right now :)"
  echo ""
  echo "for FILTR you can use:"
  echo "'-a [DATETIME]'      : returns every log after used [DATETIME]"
  echo "'-b [DATETIME]'      : returns every log before used [DATETIME]"
  echo "'-c [CURRENCY]'      : returns every log with used [CURRENCY]"
  echo ""
  echo "for PŘÍKAZ you can use:"
  echo "'list'                : returns list of every log of yours"
  echo "'list-currency'       : returns list of every currency in alphabetical order"
  echo "'status'              : returns list of every -- status of every currency you mantain"
  echo "'profit'              : returns list of every status of your currencies with the profit you made"
  echo "for UŽIVATEL use your name you had signed with"
  echo "for LOG use log"
  echo ""
  shift
  exit 0
fi

if [ "$1" = "-a" ] || [ "$1" = "-b" ] || [ "$1" = "-c" ]; then
    FLT=$1
#todo elif [ -n "$1" ]; then
#todo echo "Please call for '--help'."
shift 2
fi

if [ "$1" = "list" ] || [ "$1" = "list-currency" ] || [ "$1" = "profit" ] || [ $1 = "status" ]; then
    CMD="$1"
    shift 1
else
    CMD="list"
fi

if [ -n "$1" ]; then
    NAME="$1"
    shift 1
#todo    echo "No NAME used, please write your name on UŽIVATEL placeholder."
fi


#kktina, but ok
if [ -f "$1" ]; then #bere jen static way
    LOG="$1"
    shift 1
else
    echo "No LOG used, please put your log on LOG placeholder."
fi

if [ -f "$1" ]; then #bere jen static way
  LOG2="$1"
  #todo cyklus a mnoho logov
fi


FLT_fun()
{
    if [ $FLT = "-a" ]; then
        awk
    elif [ $FLT = "-b" ]; then
        awk
    elif [ $FLT = "-c" ]; then
        awk
    fi
}

CMD_fun ()
{
    if [ $CMD = "list" ] || [ -z $CMD ]; then
        awk
    elif [ $CDM = "list-currency" ]; then
        awk
    elif [ $CMD = "status" ]; then
        awk
    elif [ $CMD = "profit" ]; then
        awk
    fi
}

sort_for()
{
    tralala
}